#!/bin/bash



if [ -z "${CONFIG}" ] && [ ! -f "/usr/share/heartbeat/heartbeat.yml" ] ; then

  echo 'Please provide configuration in the $CONFIG environment variable'
  echo 'or mount the configuration file using -v heartbeat.yml:/usr/share/heartbeat/heartbeat.yml'
  echo 'The container cannot start without a valid configuration'
  
  exit 1

fi  

if [ -n "${CONFIG}" ]; then
   echo "$CONFIG" > /usr/share/heartbeat/heartbeat.yml
fi


if [ -n "${ES_URL}" ] && [ $(grep -c "output.elasticsearch" /usr/share/heartbeat/heartbeat.yml )  -eq 0 ]; then

    echo "output.elasticsearch:
  hosts: [\"${ES_URL}\"]" >> /usr/share/heartbeat/heartbeat.yml
    if [ -n "${ES_USER}" ] && [ -n "${ES_PASSWORD}" ]; then
    echo "  username: \"${ES_USER}\"
  password: \"${ES_PASSWORD}\" " >> /usr/share/heartbeat/heartbeat.yml

   fi
fi

if [ -n "${KIBANA_URL}" ] && [ $(grep -c "setup.kibana" /usr/share/heartbeat/heartbeat.yml )  -eq 0 ]; then
    echo "setup.kibana:
  host: \"${KIBANA_URL}\"" >> /usr/share/heartbeat/heartbeat.yml

fi

if [ -n "${ENABLE_METRICS_LOG}" ] && [ "${ENABLE_METRICS_LOG}" == "True" ];  then

    sed -i 's/logging.metrics.enabled:.*/logging.metrics.enabled: true/' /usr/share/metricbeat/metricbeat.yml

fi


exec /usr/local/bin/heartbeat-entrypoint "$@"
