#!/bin/bash

if [ -n "$CONFIG" ]; then

   echo "$CONFIG" > /usr/share/metricbeat/metricbeat.yml

fi

get_metadata(){
   
   result='Not found' 
   count=5
   timeout=5
   
   while [ "$result" == "Not found" ] && [ $count -gt 0 ]; do
      result=$(curl -s $1)
      if [ "$result" == "Not found" ]; then
        let count=$count-1
        sleep $timeout
      fi
   done

}

if [ -n "${RANCHER_METADATA}" ]; then
     
     get_metadata http://rancher-metadata/latest/self/host/hostname
     export HOSTNAME=$result
     
     get_metadata http://rancher-metadata/latest/self/stack/environment_name
     export RANCHER_ENV=$result
fi
    
generate_configuration.py

chmod go-w /usr/share/metricbeat/metricbeat.yml

exec /usr/local/bin/metricbeat-entrypoint "$@"
