#!/bin/bash

if [ -n "$CONFIG" ]; then

   echo "$CONFIG" > /usr/share/metricbeat/metricbeat.yml

fi

get_host_metadata(){
   
   count=10
   timeout=10

   #Hosts do not contain spaces, check if host is empty or contains spaces
   while ([[ "$result" =~ \  ]] || [ -z "$result" ]) && [ $count -gt 0 ]; do
      result=$(curl -s http://rancher-metadata/latest/self/host/hostname)
      if [[ "$result" =~ \  ]] || [ -z "$result" ]; then
        let count=$count-1
        sleep $timeout
      fi
   done

}


get_env_metadata(){
   
   result='Not found' 
   count=10
   timeout=10
   
   while ([[ "$result" == "Not found" ]] || [ -z "$result" ]) && [ $count -gt 0 ]; do
      result=$(curl -s http://rancher-metadata/latest/self/stack/environment_name)
      if [[ "$result" == "Not found" ]] || [ -z "$result" ];  then
        let count=$count-1
        sleep $timeout
      fi
   done

}

if [ -n "${RANCHER_METADATA}" ]; then
     
     get_host_metadata 
     export HOSTNAME=$result
     
     get_env_metadata 
     export RANCHER_ENV=$result
fi
    
generate_configuration.py

chmod go-w /usr/share/metricbeat/metricbeat.yml

if [ -n "${ADD_ETC_HOSTS}" ] && [ $(grep -c "${ADD_ETC_HOSTS}" /etc/hosts) -eq 0 ]; then
      echo "${ADD_ETC_HOSTS}" >> /etc/hosts
fi      


exec /usr/local/bin/metricbeat-entrypoint "$@"
