tags: [ ]

metricbeat.modules:
- module: docker
  metricsets:
    - "healthcheck"
  hosts: ["unix:///var/run/docker.sock"]
  period: 120s
  enabled: true
  # Replace dots in labels with `_`. Set to false to keep dots
  labels.dedot: true
- module: docker
  metricsets:
    - "diskio"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 180s
  enabled: true
  # Replace dots in labels with `_`. Set to false to keep dots
  labels.dedot: true
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "info"
    - "memory"
  hosts: ["unix:///var/run/docker.sock"]
  period: 300s
  enabled: true
  # Replace dots in labels with `_`. Set to false to keep dots
  labels.dedot: true

logging.metrics.enabled: false
