

tags: [ ${TAGS} ]
metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 60s
  enabled: true
  # Replace dots in labels with `_`. Set to false to keep dots
  labels.dedot: true

